### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by gdreelin** [postlund/home-card#14]
When you are setting this up in your WWW folder and create the home-card folder do you put the two files into that and then cope the theme directory into it? I tried to set it up like you have but it will not show any of the graphics. I think this card idea is awesome and love to get it setup but can't seem to make it working in the UI editor.

**Comment by gdreelin** [comment]
Nevermind figured it out

**Comment by Tokn59** [comment]
Would have been nice if you said how ...

**Comment by gdreelin** [comment]
> Would have been nice if you said how ...

Sorry it was not an issue with the setup which worked from the instructions given. It was a mistake on my part. Sorry I didn't state that, which is why I closed it.

**Comment by Tokn59** [comment]
No worries, got it working too ... You need to add the resource via the Lovelace interface and not via yaml.
