### ISSUE TITLE
Images are shifted.

### ISSUE THREAD

**Issue by elblogbruno** [postlund/home-card#28]
Hi,
Thanks for such an awesome repository and component for Home Assistant. I have set it up and this is happening on my side, a bit strange as you see all images are on the right side. I will investigate furthermore!

![image](https://user-images.githubusercontent.com/10481058/124162448-bb7ab080-da9e-11eb-8d2d-e4a57c7838ea.png)

Cordially,
Bruno

**Comment by avidit** [comment]
Duplicate of #25

**Comment by elblogbruno** [comment]
Oh sorry for it!
Thanks
