### ISSUE TITLE
Empty id specified in weather

### ISSUE THREAD

**Issue by rberryhill** [postlund/home-card#6]
I am having trouble configuring the card.  After entering these two lines in the Card Configuration I get the error message "Empty id specified in weather"
type: 'custom:home-card'
theme: two_story_with_garage

If I add a line for the weather using dark_sky, I get a TypeError: Cannot convert undefined or null to object
weather: weather.dark_sky

I am very new to HA so it could be my mistake.  This is how weather is defined in my configuration.yaml
weather:
  - platform: darksky
    api_key: <my api key>
    mode: daily 

weather.home -- does not exist.  It looks like weather.dark_sky is recognized but maybe it does not contain an attribute that is expected.

I appreciate your help and look forward to using the card.

**Comment by postlund** [comment]
Could you check if the entity exists and how it looks like (e.g. which attributes it has) under the dev panel? Should be the second icon from the left.

**Comment by rberryhill** [comment]
Here is a screen shot of the image.  Perhaps it is a problem with the forecast attribute?
I will see if there is a solution for that.

[cid:3bcdad29-2787-481e-b838-cbb900dfa6ff]

________________________________

**Comment by rberryhill** [comment]
By the way, the weather card is displaying correctly with dark_sky and I have the customized weather card working with it as well.  No forecast on those cards.

________________________________

**Comment by postlund** [comment]
Looks like the image upload didn't work properly, could you retry that?

I tried getting a darksky account and setting it up myself and it seems to work as expected. The card only uses `friendly_name` and `temperature` so it shouldn't be a problem with the forecast (does not look at that  at all). An obvious improvement I have to make is to include the stacktrace when displaying an error.

Can you open `home-card.js`, scroll down to `render()` and change `${error}` to `${error.stack}`? That should give more to what is happening.

**Comment by rberryhill** [comment]
The images were not copied.  I re-read the instructions and based on the clone steps, copied everything into the folder.

[cid:cab293bd-d7f8-4ec4-adb9-895d42865ff4]
[cid:2fc9283f-2478-45b8-9ea5-f40fba701e7c]
All of the files are in the themes folder but I didn't screen shot all of them.

[cid:474f7231-c5be-455b-adbb-dfb253ffd58c]

Edited home-card.js, cleared cache, rebooted - still getting undefined or null object

[cid:6b9fc690-3073-4186-9c67-5ee1b8d77246]


[cid:f8e7b7f1-f0f4-4ef1-9158-fb899a52bb11]

Thanks for you help.


________________________________

**Comment by postlund** [comment]
Are you responding to the email from GitHub? Because the images are not attached correctly to the issue. Could you upload them via the web page instead?

**Comment by rberryhill** [comment]
The images were not copied. I re-read the instructions and based on the clone steps, copied everything into the folder.
All of the files are in the themes folder but I didn't screen shot all of them.
The compressed file contains bmp images.
[w5gvwlmn.zip](https://github.com/postlund/home-card/files/2976056/w5gvwlmn.zip)
